Feat/footer
andrezzasouza/BookLand_Front-end pull request #1
Opened 2021-11-08 03:59 UTC by andrezzasouza

Footer is ready for merge.

2021-11-08 13:27 UTC, PMafra requested changes

2021-11-08 13:27 UTC, PMafra commented on src/assets/styles/FooterStyle.js
> +`;
Os últimos 5 components estão com repetição de código. Não seria melhor criar classes separadas dentro do FooterContainer para essas propriedades e usá-las com 'className' onde for preciso? Sugestão:
`.text-style {
        color: #ffffff;
        font-size: 48px;
        &:hover {
            color: #5e1919;
       }
}`
E nesse caso poderia usar direto o nome da logo. ex.:
`<IoLogoWhatsapp className="text-style" />`

2021-11-08 13:27 UTC, PMafra commented on src/components/Footer.js
> +      if (e.key === 'Escape' && showModal === true) {
Aqui talvez seria melhor:
`if (e.key === 'Escape' && showModal)`

2021-11-08 22:34 UTC, andrezzasouza commented
@PMafra I have fixed the issues. :)

2021-11-09 14:55 UTC, PMafra approved these changes

2021-11-09 14:55 UTC, merged