Feat/header
andrezzasouza/BookLand_Front-end pull request #5
Opened 2021-11-13 23:57 UTC by andrezzasouza

Header is ready for merge.

2021-11-14 15:44 UTC, PMafra requested changes

2021-11-14 15:44 UTC, PMafra commented on src/components/Header.js
> +  }
A função de logout não deveria também apagar a sessão do usuário no banco ?

2021-11-14 15:44 UTC, PMafra commented on src/components/Header.js
> +              src={jsonToken.image ? jsonToken.image : userPhoto}
O nome do atributo é 'picture' e não 'image'

2021-11-14 15:44 UTC, PMafra commented on src/pages/Home.js
> +          if (err.response.status === 500) {
Aqui acho que tem um if desnecessário. Poderia tirar o `if (err.response)` e só deixar o `if (err.response.status === 500) ` e funcionaria igual se não me engano

2021-11-14 21:47 UTC, andrezzasouza commented on src/pages/Home.js
> +          if (err.response.status === 500) {
Se o front não conseguir se conectar com o back, como no Vercel, por exemplo, dá um erro no React sem esse if. Aí seria um lugar pra usar optional chain se não tivesse o problema de compatibilidade com alguns navegadores que ainda não aceitam.

2021-11-14 21:48 UTC, andrezzasouza commented on src/components/Header.js
> +  }
Tinha feito de outra forma no MyWallet, mas vou alterar aqui.

2021-11-14 22:38 UTC, PMafra commented on src/pages/Home.js
> +          if (err.response.status === 500) {
Ah entendi, show!

2021-11-16 01:19 UTC, PMafra approved these changes

2021-11-16 01:19 UTC, merged